---
name: 🔧 Terraform CI

on:
  push:
    branches: [ main ]
    paths:
      - '*.tf'
      - '*.tfvars'
      - '.github/workflows/*'
  pull_request:
    branches: [ main ]
    paths:
      - '*.tf'
      - '*.tfvars'

jobs:
  fmt-validate:
    name: Format + Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.6

      - name: Terraform fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: Terraform init (backend=false)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
